"""Validate and export an explicit source-only allowlist; standard library only."""
import argparse
import hashlib
import json
from pathlib import Path, PurePosixPath
import re
import subprocess
import zipfile

ROOT = Path(__file__).resolve().parents[1]
ALLOWED = {'.py', '.ps1', '.cjs', '.js', '.json', '.md', '.txt'}
FORBIDDEN = {'models', 'results', 'selftest', 'tmp', 'node_modules', '__pycache__', '.cache', 'dist'}

def ignore_text(names):
    lines = ['# Generated by tools/source_release.py; unlisted files stay local.', '/*']
    dirs = set()
    for name in names:
        p = PurePosixPath(name)
        for parent in p.parents:
            if str(parent) != '.': dirs.add(parent.as_posix())
    for d in sorted(dirs, key=lambda x: (x.count('/'), x)):
        lines += ['!/'+d+'/', '/'+d+'/*']
    lines += ['!/'+name for name in names]
    return '\n'.join(lines)+'\n'

def validate(write_ignore=False):
    names = json.loads((ROOT/'SOURCE_FILES.json').read_text(encoding='utf8'))
    if not isinstance(names, list) or any(not isinstance(n,str) for n in names) or len(set(names)) != len(names):
        raise ValueError('Invalid source list')
    for name in names:
        p = PurePosixPath(name)
        if p.is_absolute() or '..' in p.parts or '\\' in name or ':' in name or p.as_posix() != name:
            raise ValueError('Unsafe path: '+name)
        if any(part in FORBIDDEN or part.startswith('.venv') for part in p.parts):
            raise ValueError('Local data forbidden: '+name)
        if name not in {'.gitignore', 'LICENSE'} and (p.suffix not in ALLOWED or (p.suffix == '.txt' and not p.name.startswith('requirements'))):
            raise ValueError('Unexpected file type: '+name)
        f = ROOT/name
        if any((ROOT/Path(*p.parts[:i])).is_symlink() or (ROOT/Path(*p.parts[:i])).is_junction() for i in range(1,len(p.parts)+1)):
            raise ValueError('Links forbidden: '+name)
        if not f.is_file() or f.stat().st_size > 2*1024*1024:
            raise ValueError('Missing or oversized source: '+name)
        text = f.read_text(encoding='utf-8-sig')
        patterns = [r'-----BEGIN (?:RSA |OPENSSH |EC )?PRIVATE KEY-----', r'gh[pousr]_[A-Za-z0-9]{30,}', r'hf_[A-Za-z0-9]{30,}', r'(?i)[A-Z]:[/\\](?:shuntian-blog|Users)[/\\]']
        if any(re.search(pattern,text) for pattern in patterns):
            raise ValueError('Potential private content; review: '+name)
    expected = ignore_text(names)
    if write_ignore: (ROOT/'.gitignore').write_text(expected,encoding='utf8')
    if (ROOT/'.gitignore').read_text(encoding='utf8') != expected:
        raise ValueError('Run --write-gitignore to synchronize rules')
    if (ROOT/'.git').exists():
        tracked = subprocess.check_output(['git','-C',str(ROOT),'ls-files','-z']).decode().split('\0')
        extra = set(filter(None,tracked))-set(names)
        if extra: raise ValueError('Tracked files outside allowlist: '+str(sorted(extra)))
    return names

def main():
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument('--check',action='store_true')
    p.add_argument('--write-gitignore',action='store_true')
    p.add_argument('--output',type=Path)
    args=p.parse_args()
    names=validate(args.write_gitignore)
    if args.output:
        out=args.output.resolve()
        if out.exists(): raise ValueError('Output already exists; choose a new name')
        out.parent.mkdir(parents=True,exist_ok=True)
        with zipfile.ZipFile(out,'x',compression=zipfile.ZIP_DEFLATED) as z:
            for name in names: z.write(ROOT/name,name)
        with zipfile.ZipFile(out) as z:
            assert set(z.namelist()) == set(names) and len(z.namelist()) == len(names)
            for name in names: assert z.read(name) == (ROOT/name).read_bytes(), name
        print('ZIP verified:',out,'sha256:',hashlib.sha256(out.read_bytes()).hexdigest())
    print('Source checks passed:',len(names),'files;',sum((ROOT/n).stat().st_size for n in names),'bytes')

if __name__ == '__main__': main()
